modLoader="javafml" 
loaderVersion="${loader_version_range}" 
license="${mod_license}"

[[mods]]
modId="${mod_id}" 
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://change.me.to.your.mods.homepage.example.invalid/" # To Do
logoFile="scalarutils6.png"
credits=""
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)" 
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="scalar_core"
    type="required"
    versionRange="[1.21.1-1.0.6,)"
    ordering="NONE"
    side="BOTH"